name: auto-update

on:
  repository_dispatch:
  push:
    branches:
      - for-next
  schedule:
    - cron: "0 18 * * *"

jobs:
  update-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.PAT }}
    - name: follow for-next
      run: |
          git fetch origin for-next
          git merge --ff-only origin/for-next
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/setup-python@v1
    - name: Update tools
      run: python update-n-freeze.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        author-name: "github-actions[bot]"
        author-email: "41898282+github-actions[bot]@users.noreply.github.com"
        commit-message: "update tools"
        title: Next image
        labels: pkg-update, auto
        assignees: pauleve
        branch: auto/next
        branch-suffix: none
        base: master
        token: ${{ secrets.GITHUB_TOKEN }}
