name: auto-update

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 21 * * *"

jobs:
  update-tools:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
    - name: Update'n freeze
      run: |
         python update-n-freeze.py
         git diff --quiet Dockerfile && exit 0
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add Dockerfile
         git commit -m "[auto] update tools"
    - name: Push changes to master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Push changes to next
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: next

