
name: Daily tagging

on:
  schedule:
    - cron: "45 23 * * *"

jobs:
  release:
    env:
      IMAGE_BASENAME: colomoto/colomoto-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Tags
        run: |
          echo ::set-env name=LATEST_TAG::$(git tag|tail -n1)
          echo ::set-env name=NEXT_TAG::$(date +%F)
      - name: Check for changes
        run: |
          echo ::set-env name=HAS_CHANGES::$(git diff --quiet $LATEST_TAG.. Dockerfile usecases tutotials || echo 1)
          echo ::set-env name=IMAGE_NAME::${IMAGE_BASENAME}:${NEXT_TAG}
      - name: Docker image build
        if: env.HAS_CHANGES == 1
        run: sh hooks/build
      - name: Docker image validation
        if: env.HAS_CHANGES == 1
        run: docker run --rm $IMAGE_NAME env validate.sh
      - name: Login to docker hub
        if: env.HAS_CHANGES == 1
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image release
        if: env.HAS_CHANGES == 1
        uses: actions-hub/docker@master
        with:
          args: push ${IMAGE_NAME}
      - name: Git tag
        if: env.HAS_CHANGES == 1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git tag $NEXT_TAG
          git push --tags https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/${GITHUB_REPOSITORY}.git HEAD:master

