name: Docker Image CI

on:
  push:
    branches: next

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        IMAGE_NAME: colomoto/colomoto-docker:next
      run: sh hooks/build
    - name: Validate
      run: docker run --rm colomoto/colomoto-docker:next validate.sh
    - name: test
      run: echo "OK"
