name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled]

jobs:
  validate:
    env:
      IMAGE_NAME: colomoto/colomoto-docker:next
      #AUTODOCKER: contains(github.event.pull_request.labels.*.name, "autodocker")
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "${{ contains(github.event.pull_request.labels.*.name, "autodocker") }}"
      #- uses: actions/checkout@v1
      #- name: Docker image build
      #  run: sh hooks/build
      #- name: Docker image validation
      #  run: docker run --rm $IMAGE_NAME env validate.sh

