name: Mirror docker images

on:
  repository_dispatch:
    types:
      - 'mirror-gh/*-*-*'
      - 'mirrors/*-*-*'
  push:
    tags:
      - '*-*-*'

jobs:
  mirror-ghcr:
    name: Release on GitHub package
    runs-on: ubuntu-latest
    steps:
      - run:
          echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
        if: github.event_name == 'push'
      - run:
          echo TAG=${REF##*/} >> $GITHUB_ENV
        if: github.event_name == 'repository_dispatch'
        env:
            REF: ${{ github.event.action }}
      - run: |
          echo IMAGE=colomoto/colomoto-docker:${TAG} >> $GITHUB_ENV
          echo MIRROR=docker.pkg.github.com/colomoto/colomoto-docker/colomoto-docker:${TAG} >> $GITHUB_ENV
      - run: docker pull ${IMAGE}
      - run: docker tag $IMAGE $MIRROR
      - name: Login to GitHub Packages
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com
      - name: Push package
        uses: actions-hub/docker@master
        with:
          args: push $MIRROR
