name: monthly merge

on:
  schedule:
    - cron: "00 19,21 01 * *"

jobs:
  monthly-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: "pascalgn/automerge-action@v0.13.0"
      env:
        GITHUB_TOKEN: "${{ secrets.PAT }}"
        MERGE_LABELS: "ready-for-monthly-merge"
        MERGE_METHOD: "rebase"
        MERGE_DELETE_BRANCH: "true"
