name: monthly merge

on:
  schedule:
    - cron: "00 19,21 01 * *"

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: squalrus/merge-bot@v0.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        labels: ready-for-monthly-merge
        checks_enabled: true
        method: rebase
        delete_source_branch: true
