name: monthly merge

on:
  schedule:
    - cron: "00 18,21 01 * *"

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-automerge-action@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        merge-method: 'rebase'
        min-approvals: 1
        base-ref: 'master'
