name: next PR auto merge

on:
  schedule:
    - cron: "00 23 28-31 * *"

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
    - run: echo ::set-env name=TOMORROW::$(date --date=tomorrow +\%d)
    - uses: davideviolante/pr-automerge-action@v1.1.0
      if: env.TOMORROW == '01'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        merge-method: 'rebase'
        min-approvals: 1
        base-ref: 'master'
